Update the README with the multiple certificates creation information
coopdevs/certbot_nginx pull request #12
Opened 2019-01-25 21:54 UTC by danypr92

Solves the issue #11

2019-01-29 08:30 UTC, enricostano requested changes

2019-01-29 08:30 UTC, enricostano commented on README.md
> +4. Generate a Let's Encrypt SSL certificates for the given `domain_name` or `domain_names`.
This is not true, the `domain_names` thing it's external to this role. That variable is not used inside this role. This role only use `domain_name` variable.

2019-01-29 08:30 UTC, enricostano commented on README.md
> +You can define the var `domain_names` and configure a role to incude the this role in a loop. See [Multiple certificates creation](#example-playbook---multiple-certificates-creation) section.
I would create a new paragraph like *Generating multiple certificates* and keep all the things (examples, explication, etc.) related to multiple domains in there.

What do you think? The idea is to explain first the easy case and then the more complex case.

2019-05-13 20:24 UTC, enricostano commented on README.md
> +    - role: coopdevs.certbot-nginx
`certbot_nginx`

2019-05-16 09:18 UTC, danypr92 commented
I apply all the changes requested @enricostano. If you don't have any request, we can merge it!

2019-05-16 09:26 UTC, enricostano approved these changes

2019-05-16 09:26 UTC, merged